application: [app-id]
version: 1
runtime: php
api_version: 1
threadsafe: true
handlers:
- url: /static
  static_dir: static
  expiration: 30d
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: .*
  script: index.php
